CREATE TABLE IF NOT EXISTS user (
    id INT UNIQUE AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
	register_date DATETIME
);
CREATE TABLE IF NOT EXISTS post(
    id INT UNIQUE AUTO_INCREMENT PRIMARY KEY,
	publish_date DATETIME NOT NULL,
	length int NOT NULL,
	user INT NOT NULL,
	topic INT NOT NULL,
	thread INT NOT NULL,
	hash VARCHAR(64) NOT NULL,
	CONSTRAINT post_user FOREIGN KEY (user)
	REFERENCES user(id) ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS topic(
    id INT UNIQUE AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	url VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS thread(
	id INT UNIQUE AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	url VARCHAR(255) NOT NULL,
	topic INT NOT NULL,
	CONSTRAINT thread_topic FOREIGN KEY (topic)
	REFERENCES topic(id) ON DELETE RESTRICT
);


